# Generated by Django 4.2.6 on 2023-10-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('slot-1', '09:00 - 12:00'), ('slot-2', '12:00 - 15:00'), ('slot-3', '15:00 - 18:00')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='UCCS Email')),
                ('major', models.CharField(choices=[('PhD-CS', 'PhD in Computer Science'), ('PhD-Sec', 'PhD in Security'), ('MS-CS', 'MS in Computer Science'), ('MS-Sec', 'MS in Security')], max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('slot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.roomslot')),
            ],
        ),
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('101-A', 'Room 101-A'), ('102-A', 'Room 102-A'), ('103-B', 'Room 103-B'), ('104-B', 'Room 103-B'), ('105-C', 'Room 105-C')], max_length=10)),
                ('slots', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.roomslot')),
            ],
        ),
    ]
