# Generated by Django 4.2.6 on 2023-10-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomslot',
            name='title',
            field=models.CharField(default='Time slot', max_length=200),
            preserve_default=False,
        ),
    ]
