# Generated by Django 4.2.6 on 2023-10-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0002_roomslot_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labroom',
            old_name='room',
            new_name='title',
        ),
    ]
