# Generated by Django 4.2.6 on 2023-11-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0004_booking_remove_labroom_slots_remove_labroom_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_time',
            new_name='slot_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
