# Generated by Django 4.2.6 on 2023-11-22 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0006_remove_student_purpose_booking_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('slot-1', '09:00 - 12:00'), ('slot-2', '12:00 - 15:00'), ('slot-3', '15:00 - 18:00')], max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='labroom',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='labroom',
            name='title',
            field=models.CharField(choices=[('101-A', 'Room 101-A'), ('102-A', 'Room 102-A'), ('103-B', 'Room 103-B'), ('104-B', 'Room 104-B'), ('105-C', 'Room 105-C')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, verbose_name='UCCS Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='labroom',
            name='slots',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.roomslot'),
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.roomslot', unique=True),
        ),
    ]
