# Generated by Django 4.2.6 on 2023-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0008_remove_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
