# Generated by Django 4.2.6 on 2023-11-22 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0010_remove_labroom_slots_roomslot_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomslot',
            name='room',
        ),
        migrations.AddField(
            model_name='labroom',
            name='slot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.roomslot'),
        ),
    ]
