# Generated by Django 4.2.6 on 2023-11-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0013_alter_labroom_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.labroom', unique=True),
        ),
    ]
