# Generated by Django 4.2.6 on 2023-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0014_alter_student_date_alter_student_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('slot', 'date')},
        ),
    ]
