# Generated by Django 4.2.6 on 2023-11-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0015_alter_student_date_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='alras_application.labroom'),
        ),
    ]
