# Generated by Django 4.2.6 on 2023-11-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0016_alter_student_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slot',
        ),
        migrations.CreateModel(
            name='SlotDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alras_application.labroom')),
            ],
            options={
                'unique_together': {('slot', 'date')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.ManyToManyField(to='alras_application.slotdate'),
        ),
    ]
