# Generated by Django 4.2.6 on 2023-11-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0017_alter_student_unique_together_remove_student_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='slot',
        ),
        migrations.DeleteModel(
            name='SlotDate',
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alras_application.labroom'),
        ),
    ]
