# Generated by Django 4.2.6 on 2023-11-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alras_application', '0018_student_date_remove_student_slot_delete_slotdate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('slot', 'date')},
        ),
    ]
